export { LogoNeoflex } from "./logoNeoFlex";
export { EmailIcon } from "./emailIcon";
export { SendIcon } from "./sendIcon";
export { MapIcon } from "./mapIcon";
export { BankIcon } from "./bankIcon";
export { PersonIcon } from "./personIcon";
export { ArrowSliderIcon } from "./arrowSliderIcon";
export {MoneyIcon } from "./moneyIcon";
export {CalendarIcon } from "./calendarIcon";
export {ClockIcon} from "./clockIcon";
export {BagIcon} from "./bagIcon";
export {CreditCardIcon} from "./creditCardIcon";
export {ArrowIcon} from "./arrowIcon";
