export { Header } from "./header";
export { Footer } from "./footer";
export { EmailSubscribe } from "./emailSubscribe";
export { MapSection } from "./mapSection";
export { Currency } from "./currency";
export { YouCanUse } from "./youCanUse";
export { ChooseCards } from "./chooseCards";
export { News } from "./news";
export {InfoCard } from "./infoCard";
export {AboutCard} from './aboutCard';
export {DetailInfo } from "./detailInfo";
export {RatesConditions} from "./ratesConditions";
export {Cashbacks} from "./cashbacks";
export {Faq} from "./faq";
export {Steps} from "./steps";
export {FormPrescoring} from "./formPrescoring";
export {NotFound} from "./notfound";